version: '3.8'
services:
  backend:
    build: ./Backend
    volumes:
      - ./Backend:/app
      - static_volume:/app/static
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=sqlite:///./tareas_database.sqlite

volumes:
  static_volume: